Repository ELS-RD/kernl, pull requests merged in 2022-11, with the labels that each got.

#144 fix: remove fx profiler
  requirements.txt
  src/kernl/utils/fx_profiler.py
  tutorial/2 - matmul offsets.ipynb
Labels: dependencies, fix

#134 feat: update to PyTorch 1.14
  Dockerfile
  README.md
  conftest.py
  requirements.txt
  setup.py
  src/kernl/model_optimization.py
  test/models/bert.py
  test/test_model_optimization.py
  test/test_torchdynamo.py
  tutorial/bert e2e.ipynb
  tutorial/t5 e2e.ipynb
Labels: feature, dependencies

#147 fix: rename all close
  conftest.py
  test/test_attention.py
  test/test_batched_matmul.py
  test/test_debugger.py
  test/test_layer_norm.py
  test/test_linear_layer.py
  test/test_torchdynamo.py
Labels: fix

#116 feat: improve debugger api
  src/kernl/utils/debugger.py
  test/test_debugger.py
Labels: enhancement, feature

#112 docs: add static documentation website
  .github/workflows/deploy-static-site.yml
  .gitignore
  docs/README.md
  docs/assets/favicon.png
  docs/assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
  docs/assets/images/curve-mask-bottom.svg
  docs/assets/images/curve-mask-top-contribute.svg
  docs/assets/images/curve-mask-top.svg
  docs/assets/images/icon-atom.svg
  docs/assets/images/icon-bear.svg
  docs/assets/images/icon-handyman.svg
  docs/assets/images/icon-lotus.svg
  docs/assets/images/icon-open-source.svg
  docs/assets/images/icon-team.svg
  docs/assets/images/logo-ls.svg
  docs/assets/images/logo.svg
  docs/changelog/page.md
  docs/contribution-guide/page.md
  docs/get-started/start.md
  docs/how-it-works/page.md
  docs/index.md
  docs/javascripts/extra.js
  docs/javascripts/gsap.3.11.0.min.js
  docs/javascripts/mathjax.js
  docs/javascripts/scrollTrigger.3.11.0.min.js
  docs/overrides/404.html
  docs/overrides/home.html
  docs/overrides/main.html
  docs/reference/page.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: feature

#157 fix: removes the noindex meta.
  docs/overrides/main.html
Labels: fix

#155 feat: add stale workflow
  .github/workflows/stale.yml
Labels: enhancement, feature

#158 fix: attention bug with large values
  src/kernl/implementations/attention.py
  test/test_attention.py
Labels: fix

#162 feat: only close issues marked as questions
  .github/workflows/stale.yml
Labels: enhancement, feature

#160 feat: monthly triton update
  requirements.txt
Labels: feature, dependencies

#163 feat: check stability of output
  src/kernl/implementations/attention_masked_original.py
  src/kernl/implementations/attention_original.py
  test/test_attention.py
Labels: feature

#150 docs: install instructions simplification
  README.md
Labels: documentation

#168 feat: better precision when the mask is big (covers lots of tokens)
  src/kernl/implementations/attention.py
  test/test_attention.py
Labels: bug, feature

#175 feat: remove nvfuser
  test/models/bert.py
  test/test_torchdynamo.py
Labels: benchmark

#177 fix: bug where some specific shapes make inference on cuda graphs crashing
  src/kernl/implementations/attention.py
  test/test_torchdynamo.py
Labels: triton, fix

#172 feat: add autotune to optimize attention speed
  Makefile
  conftest.py
  src/kernl/implementations/attention.py
  test/test_attention.py
  test/test_debugger.py
Labels: feature, triton, performance

#171 feat: implements highlighted features in the static site.
  docs/assets/images/highlight-efficiency.svg
  docs/assets/images/highlight-performance.png
  docs/javascripts/extra.js
  docs/overrides/home.html
  docs/stylesheets/extra.css
Labels: feature

#186 feat: add google analytics (ga4) and cookie consent.
  mkdocs.yml
Labels: feature

#190 fix: layernorm stride
  src/kernl/implementations/layer_norm.py
  test/test_layer_norm.py
Labels: fix

#192 fix: support stride for layernorm when dim is more than 3
  src/kernl/implementations/layer_norm.py
Labels: fix
