Repository ELS-RD/kernl, pull requests merged in 2022-10, with the labels that each got.

#124 fix: python version
  setup.py
Labels: bug, fix

#126 fix: change python version
  setup.py
Labels: fix

#107 feat: layernorm rms replacement for T5
  src/kernl/optimizer/dynamo_backend.py
  src/kernl/optimizer/layer_norm.py
  src/kernl/utils/extended_matcher.py
Labels: feature

#128 docs: update install steps
  README.md
Labels: documentation

#130 fix: pin Pytorch version to 1.12.1
  README.md
  requirements.txt
Labels: bug

#127 feat: update notebook T5
  README.md
  tutorial/t5 e2e.ipynb
Labels: documentation, feature
