Repository ELS-RD/kernl, pull requests merged in 2022-12, with the labels that each got.

#191 feat: add performance dynamic chart.
  docs/javascripts/chart.4.0.1.js
  docs/javascripts/charts-data.js
  docs/javascripts/charts.js
  docs/javascripts/extra.js
  docs/overrides/home.html
  docs/overrides/main.html
  docs/stylesheets/extra.css
Labels: feature

#198 feat: attention for skinny Q tensor
  experimental/misc/README.md
  experimental/misc/dot_perf.py
  experimental/misc/transpose.py
  src/kernl/implementations/attention_skinny.py
  src/kernl/implementations/attention_vec_mat.py
  src/kernl/implementations/cuda_graph.py
  test/test_attention.py
Labels: feature, performance

#209 fix: site deployment workflow miss mkdocstrings python handler
  .github/workflows/deploy-static-site.yml
Labels: fix

#122 feat: openai whisper support
  src/kernl/implementations/attention.py
  src/kernl/optimizer/attention.py
  src/kernl/optimizer/dynamo_backend.py
  src/kernl/optimizer/linear.py
  test/data/whisper_input.pt
  test/test_torchdynamo.py
Labels: model, feature

#210 fix: disabled search field on landing page.
  mkdocs.yml
Labels: fix

#211 feat: update triton
  requirements.txt
Labels: feature

#218 fix: missing dependency
  requirements.txt
Labels: fix

#220 feat: update torch and modify cuda graphs
  Dockerfile
  requirements.txt
  src/kernl/implementations/cuda_graph.py
  src/kernl/model_optimization.py
  test/models/bert.py
  test/test_attention.py
  test/test_layer_norm.py
  test/test_linear_layer.py
Labels: feature, dependencies
