Repository ELS-RD/kernl, pull requests merged in 2023-02, with the labels that each got.

#268 feat: reduce memory overhead in CUDA Graph
  Dockerfile
  experimental/benchmarks/inductor.py
  experimental/benchmarks/onnxrt.py
  experimental/benchmarks/tensorrt_.py
  experimental/misc/dot_perf.py
  experimental/whisper/speedup.ipynb
  src/kernl/benchmark/benchmark_session.py
  src/kernl/implementations/linear_layer.py
  src/kernl/optimizer/cuda_graph.py
  src/kernl/optimizer/pool_cuda_graphs.py
  src/kernl/utils/extended_matcher.py
  test/test_cuda_graph.py
Labels: feature, performance

#269 feat: add links to tutorials on README.md
  README.md
Labels: feature

#271 fix: remove old debugger doc
  docs/reference/debugger.md
  mkdocs.yml
Labels: fix

#274 docs: add dynamo code to notebook as a comment
  experimental/whisper/speedup.ipynb
Labels: documentation

#279 fix: correct stride for act inputs in linear layer
  src/kernl/implementations/linear_layer.py
Labels: fix

#278 chore(main): release 0.2.1
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, ignore-for-release

#284 chore: upgrade m4m to 4.30.2
  .github/workflows/deploy-static-site.yml
  docs/Dockerfile.mkdocstrings
  docs/README.md
Labels: ignore-for-release

#291 fix: fix 0 stride in CG pool management
  src/kernl/optimizer/pool_cuda_graphs.py
Labels: fix

#292 chore(main): release 0.2.2
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, ignore-for-release

#294 feat: github runner
  .github/workflows/test.yaml
Labels: feature

#300 feat: make pytest in CI non verbose
  .github/workflows/test.yaml
Labels: unit test
