Repository ELS-RD/kernl, pull requests merged in 2023-03, with the labels that each got.

#303 fix: removes/comments empty sections and navigations.
  docs/overrides/home.html
  mkdocs.yml
Labels: fix

#309 feat: m4m and kernl front optimization
  .github/workflows/deploy-static-site.yml
  .github/workflows/test.yaml
  .gitignore
  docs/Dockerfile.mkdocstrings
  docs/README.md
  docs/assets/images/404-light.svg
  docs/contribution-guide/how-to-contribute.md
  docs/overrides/404.html
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: feature

#312 feat: linking kernl and the blog
  docs/assets/images/icon-open-in-new.svg
  docs/overrides/.icons/lefebvre-sarrut/icon-social-ai-blog.svg
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: feature

#307 feat: update to triton 2.0 backend
  .github/workflows/test.yaml
  Dockerfile
  README.md
  docs/how-to-guides/get-started.md
  experimental/misc/README.md
  requirements.txt
  src/kernl/implementations/attention.py
  src/kernl/implementations/attention_skinny.py
  src/kernl/implementations/attention_vec_mat.py
  test/test_attention.py
Labels: feature, dependencies

#285 docs: add automatic code reference generation
  .github/workflows/deploy-static-site.yml
  Dockerfile
  docs/Dockerfile.mkdocstrings
  docs/gen_ref_pages.py
  docs/reference/extended_matcher.md
  docs/reference/model_optimization.md
  mkdocs.yml
  src/__init__.py
Labels: documentation

#315 feat: simplify dependencies
  .github/workflows/test.yaml
  Dockerfile
  README.md
  docs/how-to-guides/get-started.md
  requirements.txt
  src/kernl/implementations/linear_layer.py
Labels: documentation, dependencies
