Repository ELS-RD/kernl, pull requests merged in 2023-01, with the labels that each got.

#231 fix: fix flake8 config
  Makefile
  setup.cfg
Labels: fix

#225 feat: reduce cg memory footprint
  Dockerfile
  conftest.py
  experimental/whisper/script_whisper.py
  requirements.txt
  src/kernl/implementations/attention_vec_mat.py
  src/kernl/implementations/cuda_graph.py
  src/kernl/model_optimization.py
  src/kernl/optimizer/attention.py
  src/kernl/optimizer/cuda_graph.py
  test/models/bert.py
  test/test_attention.py
  test/test_layer_norm.py
  test/test_linear_layer.py
  test/test_torchdynamo.py
Labels: performance

#235 fix: stop regenerating graph module
  experimental/whisper/script_whisper.py
  src/kernl/utils/extended_matcher.py
Labels: bug, performance, fix

#243 fix: test crashing on cuda graph
  conftest.py
  src/kernl/benchmark/benchmark_fixture.py
  src/kernl/optimizer/cuda_graph.py
  test/test_torchdynamo.py
Labels: fix

#251 fix: update README with GPU requirements
  README.md
Labels: fix

#250 feat: add navigation footer.
  mkdocs.yml
Labels: feature

#216 fix: attention refactor and base doc
  docs/contribution-guide/kernel-writing-conventions.md
  mkdocs.yml
  src/kernl/implementations/attention.py
  src/kernl/implementations/attention_skinny.py
  src/kernl/implementations/attention_vec_mat.py
  src/kernl/implementations/batched_matmul.py
  src/kernl/implementations/layer_norm.py
  src/kernl/implementations/linear_layer.py
Labels: fix

#255 fix: update pytorch nightly to fix memory leak
  Dockerfile
  requirements.txt
  src/kernl/optimizer/cuda_graph.py
Labels: bug, fix

#181 docs: how to support a new model tutorial
  docs/get-started/start.md
  docs/how-to-guides/attention.drawio.svg
  docs/how-to-guides/attention_fused.drawio.svg
  docs/how-to-guides/attention_original.png
  docs/how-to-guides/fx_graph.drawio.svg
  docs/how-to-guides/get-started.md
  docs/how-to-guides/support-new-model.md
  docs/how-to-guides/torchfx.drawio.svg
  docs/overrides/home.html
  docs/tutorials/page.md
  mkdocs.yml
Labels: feature

#257 feat: replace whisper script by notebook + test fix
  Dockerfile
  README.md
  conftest.py
  experimental/whisper/README.md
  experimental/whisper/script_whisper.py
  experimental/whisper/speedup.ipynb
  src/kernl/implementations/attention.py
  src/kernl/optimizer/attention.py
  test/test_torchdynamo.py
Labels: bug, feature

#265 fix: update dep + fix
  Dockerfile
  README.md
  experimental/whisper/README.md
  requirements.txt
  src/kernl/optimizer/cuda_graph.py
  test/test_attention.py
  test/test_layer_norm.py
  test/test_linear_layer.py
Labels: bug, dependencies, fix
